version: '3.8'
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb-con
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-con
    # ports:
    #   - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
      - logs:/app/logs
    env_file:
      - ./env/server.env
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-con
    # ports:
    #   - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-con
    ports:
      - '5000:80'
    depends_on:
      - server
      - client
volumes:
  data:
  logs:
